site_name: scip-ex
site_description: scip 解题集
repo_url: https://github.com/brade1314/scip-ex/
site_author: brade
google_analytics: ['UA-135750432-1', 'sicp-ex.readthedocs.io']
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - scheme


pages:
    - 主页: index.md
    - 1.构造过程抽象: 
               - 1.1 程序设计的基本元素: chp1/1.md
               - 1.2 过程与它们所产生的计算: chp1/2.md
               - 1.3 用高阶函数做抽象: chp1/3.md
    - 2.构造数据抽象:
               - 2.1 数据抽象导引: chp2/1.md
               - 2.2 层次性数据和闭包性质: chp2/2.md
               - 2.3 符号数据: chp2/3.md
               - 2.4 抽象数据的多重表示: chp2/4.md
               - 2.5 带有通用型操作的系统: chp2/5.md
    - 3.模块化、对象和状态: 
               - 3.1 赋值和局部状态: chp3/1.md
               - 3.2 求值的环境模型: chp3/2.md
               - 3.3 用变动数据做模拟: chp3/3.md
               - 3.4 并发：时间是一个本质问题: chp3/4.md
               - 3.5 流: chp3/5.md
    - 4.元语言抽象: 
               - 4.1 元循环求值器: chp4/1.md
               - 4.2 Scheme 的变形 -- 惰性求值: chp4/2.md
               - 4.3 Scheme 的变形 -- 非确定性求值: chp4/3.md
               - 4.4 逻辑程序设计: chp4/4.md
    - 5.寄存器机器里的计算: 
               - 5.1 寄存器机器的设计: chp5/1.md
               - 5.2 一个寄存器机器模拟器: chp5/2.md
               - 5.3 存储分配和废料收集: chp5/3.md
               - 5.4 显式控制的求值器: chp5/4.md
               - 5.5 编译: chp5/5.md
               

markdown_extensions:
    - smarty
    - abbr
    - admonition
    - toc:
        permalink: true
        separator: "_"

plugins:
    - search
